<a href="https://colab.research.google.com/github/VenkataramananS/TensorflowMasterclass/blob/main/00_tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

most fundamental concepts of tensor using tensorflow.

Topics covered:


1.   Introduction to tensors
2.   Getting more info from tensors
3.   Manipulating tensors
4.   Tensors and Numpy5. Using tf.dunction ( a way to speed up regular        python functions)
6.   Using GPUs with tensorflow or (TPUs) 
7.   Exercises

## Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
# Create tensors with tf.constants()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimensions in Tensor (ndim stands number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of a vector
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the dimension of a matrix
matrix.ndim

2

In [8]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]
                       ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [9]:
# Check the dimension of a tensor
tensor.ndim

3

### Creating variables with tf.Variable

In [10]:
# Create same tensor with tf.Variable() as above
variable_tensor = tf.Variable([10,7])
constant_tensor = tf.constant([10,7])
variable_tensor,constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# Let's try to change one of the element in the variable tensor
variable_tensor[0] = 7
variable_tensor

TypeError: ignored

In [12]:
# now replacing value using .assign() function
variable_tensor[0].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [13]:
# now trying the same in the constant tensor
constant_tensor[0].assign(7)

AttributeError: ignored

### Creation of random tensors

In [14]:
# Create two tensors (but the same)
r1 = tf.random.Generator.from_seed(10)
r1 = r1.normal(shape=(3,2))
r2 = tf.random.Generator.from_seed(10)
r2 = r2.normal(shape=(3,2))

# Are they same?
r1,r2,r1==r2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

In [15]:
# Shuffle a tensor
unshuffled = tf.constant([[[10,7,6],[2,5,3],[1,4,9]],[[20,17,16],[12,15,13],[11,14,19]],[[30,27,26],[22,25,23],[21,24,29]]])
unshuffled.ndim,unshuffled

(3, <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[10,  7,  6],
         [ 2,  5,  3],
         [ 1,  4,  9]],
 
        [[20, 17, 16],
         [12, 15, 13],
         [11, 14, 19]],
 
        [[30, 27, 26],
         [22, 25, 23],
         [21, 24, 29]]], dtype=int32)>)

In [16]:
tf.random.shuffle(unshuffled)

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[20, 17, 16],
        [12, 15, 13],
        [11, 14, 19]],

       [[30, 27, 26],
        [22, 25, 23],
        [21, 24, 29]],

       [[10,  7,  6],
        [ 2,  5,  3],
        [ 1,  4,  9]]], dtype=int32)>

### Home Work Exercise
read -> https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Create 5 random tensors and shuffle them

In [17]:
rv1 = tf.constant([[1,7],[2,8]])
print(rv1.ndim)
print("Same Seed ",tf.random.shuffle(rv1,seed = 9))
print("Same Seed ",tf.random.shuffle(rv1,seed = 9))
print("Different Seed ",tf.random.shuffle(rv1,seed = 6))

2
Same Seed  tf.Tensor(
[[2 8]
 [1 7]], shape=(2, 2), dtype=int32)
Same Seed  tf.Tensor(
[[2 8]
 [1 7]], shape=(2, 2), dtype=int32)
Different Seed  tf.Tensor(
[[1 7]
 [2 8]], shape=(2, 2), dtype=int32)


In [18]:
rv2 = tf.constant([[1,7],[2,8],[3,9]])
print(rv2.ndim)
print("Same Seed ",tf.random.shuffle(rv2,seed = 9))
print("Same Seed ",tf.random.shuffle(rv2,seed = 9))
print("Different Seed ",tf.random.shuffle(rv2,seed = 6))

2
Same Seed  tf.Tensor(
[[2 8]
 [1 7]
 [3 9]], shape=(3, 2), dtype=int32)
Same Seed  tf.Tensor(
[[3 9]
 [2 8]
 [1 7]], shape=(3, 2), dtype=int32)
Different Seed  tf.Tensor(
[[3 9]
 [2 8]
 [1 7]], shape=(3, 2), dtype=int32)


In [19]:
rv3 = tf.constant([[[1,7]],[[2,8]],[[3,9]]])
print(rv3.ndim)
print("Same Seed ",tf.random.shuffle(rv3,seed = 9))
print("Same Seed ",tf.random.shuffle(rv3,seed = 9))
print("Different Seed ",tf.random.shuffle(rv3,seed = 6))

3
Same Seed  tf.Tensor(
[[[1 7]]

 [[2 8]]

 [[3 9]]], shape=(3, 1, 2), dtype=int32)
Same Seed  tf.Tensor(
[[[3 9]]

 [[2 8]]

 [[1 7]]], shape=(3, 1, 2), dtype=int32)
Different Seed  tf.Tensor(
[[[2 8]]

 [[1 7]]

 [[3 9]]], shape=(3, 1, 2), dtype=int32)


In [20]:
rv4 = tf.constant([[[1,7],[11,17]],[[2,8],[12,18]],[[3,9],[13,19]]])
print(rv4.ndim)
print("Same Seed ",tf.random.shuffle(rv4,seed = 9))
print("Same Seed ",tf.random.shuffle(rv4,seed = 9))
print("Different Seed ",tf.random.shuffle(rv4,seed = 6))

3
Same Seed  tf.Tensor(
[[[ 1  7]
  [11 17]]

 [[ 3  9]
  [13 19]]

 [[ 2  8]
  [12 18]]], shape=(3, 2, 2), dtype=int32)
Same Seed  tf.Tensor(
[[[ 1  7]
  [11 17]]

 [[ 2  8]
  [12 18]]

 [[ 3  9]
  [13 19]]], shape=(3, 2, 2), dtype=int32)
Different Seed  tf.Tensor(
[[[ 1  7]
  [11 17]]

 [[ 2  8]
  [12 18]]

 [[ 3  9]
  [13 19]]], shape=(3, 2, 2), dtype=int32)


In [21]:
rv5 = tf.constant([[[1,7,-1],[11,17,-11]],[[2,8,-2],[12,18,-12]],[[3,9,-3],[13,19,-13]]])
print(rv5.ndim)
print("Same Seed ",tf.random.shuffle(rv5,seed = 9))
print("Same Seed ",tf.random.shuffle(rv5,seed = 9))
print("Different Seed ",tf.random.shuffle(rv5,seed = 6))

3
Same Seed  tf.Tensor(
[[[  3   9  -3]
  [ 13  19 -13]]

 [[  2   8  -2]
  [ 12  18 -12]]

 [[  1   7  -1]
  [ 11  17 -11]]], shape=(3, 2, 3), dtype=int32)
Same Seed  tf.Tensor(
[[[  1   7  -1]
  [ 11  17 -11]]

 [[  2   8  -2]
  [ 12  18 -12]]

 [[  3   9  -3]
  [ 13  19 -13]]], shape=(3, 2, 3), dtype=int32)
Different Seed  tf.Tensor(
[[[  3   9  -3]
  [ 13  19 -13]]

 [[  1   7  -1]
  [ 11  17 -11]]

 [[  2   8  -2]
  [ 12  18 -12]]], shape=(3, 2, 3), dtype=int32)


### Other ways to make tensors

In [22]:
# Create a tensor of all ones
tf.ones([3,4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [23]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turning numpy arrays into tensors

The main difference between Numpy and a tensor is that Tensor uses GPU to run whereas numpy uses the CPU

In [24]:
import numpy as np

In [25]:
numpy_A = np.arange(1,25,dtype=np.int32) # Create numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
a = tf.constant(numpy_A,shape = (2,3,4)) # cumulative multiplication value of shape should match the total numbers of the numpy array i.e 2*3*4 => 24 == 24(numpy array shape)
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting more information from the tensors

When dealing with Tensors


1.   Shape
2.   Rank
3.   Axis or Dimension
4.   Size



In [27]:
# Create a rank 4 tensor (4 dimension)

rnk_4_tensor = tf.zeros(shape=[2,3,4,5])
rnk_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
print("Shape --> ",rnk_4_tensor.shape,'\nDimension --> ',rnk_4_tensor.ndim,'\nTotal number of elements --> ',tf.size(rnk_4_tensor).numpy(),"\nDatatype --> ",rnk_4_tensor.dtype)

Shape -->  (2, 3, 4, 5) 
Dimension -->  4 
Total number of elements -->  120 
Datatype -->  <dtype: 'float32'>


### Indexing Tensors
Tensors can also be indexed similar to python lists

In [29]:
# Get to first to elements in each dimension
rnk_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

## Changing or adding an extra dimension to a sensor

In [30]:
# Create a 2-dim tensor
rank_2_numpy = np.zeros(shape=(2,2))
rank_2_numpy
rank_2_tensor = tf.constant(rank_2_numpy)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0., 0.],
       [0., 0.]])>

In [31]:
# Adding an extra dimension
modified_tensor = rank_2_tensor[...,tf.newaxis] # ... represents every axis before last one, it is a replacement of : model
modified_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float64, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]])>

In [32]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float64, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]])>

In [33]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float64, numpy=
array([[[0., 0.],
        [0., 0.]]])>

In [34]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=float64, numpy=
array([[[0., 0.]],

       [[0., 0.]]])>

### Manipulation of Tensors ( Tensor Operations)
** Basic Operation **

=,-,*,/

In [35]:
tensor = tf.constant([[10,7],[3,4]])
print("Add ",tensor + 10)
print("Sub ",tensor - 10)
print("Mul ",tensor * 10)
print("Div ",tensor / 10)
print("Non float div ",tensor // 10)

Add  tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
Sub  tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
Mul  tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
Div  tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)
Non float div  tf.Tensor(
[[1 0]
 [0 0]], shape=(2, 2), dtype=int32)


In [36]:
# We can use Tensorflow built-in function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix Multiplication

In [37]:
mat1 = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])
mat2 = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])

mat_mul = tf.linalg.matmul(mat1,mat2)
mat_mul,mat_mul.shape

(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]], dtype=int32)>, TensorShape([1, 3, 3]))

In [38]:
mat3 = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])
print(mat3.shape)
print(tf.reshape(mat3,shape=(3,1,3))) # in tensor reshape the total number of elements after reshape should remain same as that of the original

(1, 3, 3)
tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]], shape=(3, 1, 3), dtype=int32)


# ** The dot product **
Matrix multiplication can be performed using


1.   tf.matmul()
2.   tf.tensordot()



In [39]:
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])


In [40]:

# Matrix multiplication between X and Y with Y transpose
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [41]:
# Matrix multiplication between X and Y with Y reshaped
tf.tensordot(X,tf.reshape(Y,shape=(2,3)),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [42]:
# Matrix multiplication between X and Y with Y transpose
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [43]:
# Check value of Y , reshape Y and transpose Y
print("Normal Y: ",Y)
print("Reshape Y: ",tf.reshape(Y,shape=(2,3)))
print("Transpose Y: ",tf.transpose(Y))

Normal Y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Reshape Y:  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Transpose Y:  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing Datatype of the tensor

In [44]:
val = tf.constant([1,2.2])
val.dtype

tf.float32

In [45]:
# Changing datatype of a tensor
tf.cast(val,dtype = tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>

## Squeezing a tensor (removing all single dimensions i.e dimensions with value one)

In [46]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [47]:
tensor_squeezed = tf.squeeze(tensor)
tensor_squeezed,tensor_squeezed.shape,tensor_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]), 1)

### Exercises

1. Creating scalar, vector, matrix and tensor using tf.constant()

In [57]:
sclr = tf.constant(10)

vctr = tf.constant([1,2])

mtrx = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

tnsr = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],
                   [[1,2,3],[4,5,6],[7,8,9]],
                   [[1,2,3],[4,5,6],[7,8,9]]])

sclr.ndim,vctr.ndim,mtrx.ndim,tnsr.ndim

(0, 1, 2, 3)

2. finding shape, rank and size of a tensor

In [60]:
tf.shape(tnsr),tf.rank(tnsr),tf.size(tnsr)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=27>)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [81]:
rndtnsr_1 = tf.random.uniform(
(5,300),
minval=0,
maxval=1,
dtype=tf.dtypes.float32,
seed=1,
name=None)
# r1 = r1.normal(shape=(5,300))

rndtnsr_2 = tf.random.uniform(
(5,300),
minval=0,
maxval=1,
dtype=tf.dtypes.float32,
seed=2,
name=None)
# r1 = r1.normal(shape=(5,300))
rndtnsr_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.39523065, 0.7226076 , 0.18639839, ..., 0.94377136, 0.16984892,
        0.9312178 ],
       [0.7145592 , 0.9608276 , 0.40824294, ..., 0.7099403 , 0.03017771,
        0.23705626],
       [0.13121116, 0.08444428, 0.43893087, ..., 0.35159528, 0.8571476 ,
        0.4827422 ],
       [0.5948739 , 0.6484932 , 0.25320458, ..., 0.54546165, 0.55536425,
        0.4920857 ],
       [0.44004762, 0.5941901 , 0.93089414, ..., 0.06279635, 0.5477712 ,
        0.59064865]], dtype=float32)>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [83]:
tf.matmul(rndtnsr_1,tf.reshape(rndtnsr_2,shape=(300,5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.70348 , 72.355515, 74.78462 , 74.42514 , 80.81511 ],
       [76.95586 , 79.99983 , 77.88314 , 77.867905, 84.056274],
       [76.36487 , 76.741196, 78.56679 , 76.82883 , 80.81122 ],
       [77.038956, 77.376785, 82.71488 , 81.48168 , 82.95416 ],
       [80.57257 , 81.36941 , 80.1617  , 82.51197 , 84.59767 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [87]:
tf.tensordot(rndtnsr_1,tf.reshape(rndtnsr_2,shape=(300,5)),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.70348 , 72.355515, 74.78462 , 74.42514 , 80.81511 ],
       [76.95586 , 79.99983 , 77.88314 , 77.867905, 84.056274],
       [76.36487 , 76.741196, 78.56679 , 76.82883 , 80.81122 ],
       [77.038956, 77.376785, 82.71488 , 81.48168 , 82.95416 ],
       [80.57257 , 81.36941 , 80.1617  , 82.51197 , 84.59767 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
rndtnsr_3 = tf.random.uniform(
(224, 224, 3),
minval=0,
maxval=1,
dtype=tf.dtypes.float32,
seed=None,
name=None)

rndtnsr_3

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
tf.reduce_min(rndtnsr_3,axis=1),tf.reduce_max(rndtnsr_3,axis=1)

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [96]:
rndtnsr_4 = tf.random.Generator.from_seed(10)
rndtnsr_4 = rndtnsr_4.normal(shape=(1, 224, 224, 3))
rndtnsr_4_squeezed = tf.squeeze(rndtnsr_4)
rndtnsr_4.shape,rndtnsr_4_squeezed.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [117]:
import random
# samples = random.sample(range(1, 100), 10)
samples = [1,2,3,4,5,6,7,8,9,10]
my_tensor = tf.constant(samples,shape=(10))
my_tensor,tf.argmax(my_tensor)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9>)

10. One-hot encode the tensor you created in 9.

In [118]:
tf.one_hot(samples,depth=10,on_value='here',off_value="no")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'no', b'here', b'no', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'here', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'here', b'no', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'here', b'no', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'here', b'no', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'here', b'no', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'here', b'no',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'here',
        b'no'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no',
        b'here'],
       [b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no', b'no',
        b'no']], dtype=object)>

[39, 49, 32, 18, 29, 25, 11]